server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      password: ${sky.redis.password}

mybatis:
  # mapper setting
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    # enable camel-case
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # jwt secret key
    admin-secret-key: itcast
    # setting jwt ttl
    admin-ttl: 7200000
    # token name
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid: ${WECHAT_APP_ID}
    secret: ${WECHAT_SECRET}

# aws
aws:
  s3:
    endpoint: ${sky.aws.s3.endpoint}
    bucket-name: ${sky.aws.s3.bucket-name}
    region: ${sky.aws.s3.region}
    access-key: ${sky.aws.s3.access-key}
    secret-key: ${sky.aws.s3.secret-key}


# swagger

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html