sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  aws:
    s3:
      endpoint: s3.amazonaws.com
      bucket-name: sky-take-out-b
      region: eu-west-1
      access-key: ${SKY_TAKE_OUT_ACCESS_KEY}
      secret-key: ${SKY_TAKE_OUT_ACCESS_PASSWORD}