version: '3.8' # docker compose file version
services:
  mysql:
    image: mysql:8.0.33 # mysql version
    container_name: mysql # container name
    environment:
      # root password
      MYSQL_ROOT_PASSWORD: 123456
      # initialize database
      MYSQL_DATABASE: sky_take_out
    ports:
      - "3306:3306"
    volumes:
      # mount data
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
volumes:
  mysql_data: